Repository kwizapp/metadata-service, pull requests merged in 2020-03, with the labels that each got.

#11 Implement functionality for random, different movie fetching
  .sonarcloud.properties
  Preprocessing.ipynb
  Preprocessing.py
  README.md
  package-lock.json
  package.json
  src/dbService.js
  src/index.js
  src/utils.js
  test/e2e.test.js
Labels: feature

#14 Update API doc in readme
  README.md
Labels: documentation

#20 Update README.md
  README.md
Labels: enhancement
