Repository kwizapp/metadata-service, pull requests merged in 2020-05, with the labels that each got.

#46 Documentation updates
  README.md
  src/dbService.js
  src/index.js
  src/utils.js
Labels: documentation

#47 Update link to API in the wiki
  README.md
Labels: documentation

#50 Separate production and staging environments
  .github/workflows/main.yml
Labels: devops

#52 Add release-drafter action
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: devops

#54 📝 add repo structure to README
  README.md
Labels: documentation

#55 Release v1.0.1
  README.md
  package-lock.json
  package.json
Labels: coordination
